controllers:
    resource:
        path: ../src/UI/Controller
        namespace: App\UI\Controller\
    type: attribute


app_domain_controllers:
    resource:
        path: ../src/UI/Controller
        namespace: App\UI\Controller
    type: attribute

# app_test_controllers:
#     resource:
#         path: ../src/some
#         namespace: App\some
#     type: attribute


app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }    