controllers:
    resource:
        path: ../src/Controller
        namespace: App\Controller\
    type: attribute


app_domain_controllers:
    resource:
        path: ../src/Domain
        namespace: App\Domain\
    type: attribute

# app_test_controllers:
#     resource:
#         path: ../src/some
#         namespace: App\some
#     type: attribute
