nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
            - ^/api(?!/doc$)
        # host_patterns: # document only routes with a host of the form api.*
        #     - ^api
    documentation:
        info:
            title: Project
            description: This is an awesome !
            version: 1.0.0
            x-build: #CommitHash